import SqueezeFilm.Core
import SqueezeFilm.Analysis.RealInstances
import SqueezeFilm.Analysis.Variational
import SqueezeFilm.Analysis.Profile
import SqueezeFilm.Analysis.Corner
import SqueezeFilm.Analysis.Strip
import SqueezeFilm.Analysis.Taper
import SqueezeFilm.Analysis.Series
import SqueezeFilm.Analysis.GeometricMean
